/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package happycup;

import java.awt.TrayIcon;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * @author FaHad
 * Programed By Fahad ALfaify
 * www.fahad.alfaify.net
 */
public class happycup extends javax.swing.JFrame {

    /**
     * Creates new form IceCreamSelling
     */
    public class Item {

        public String _type;// Vanilla,Chocolate,Strawberry,Tofee
        public boolean _almonds;
        public boolean _peanut;
        public boolean _mint;
        public boolean _peach;
        public boolean _lemon;
        public boolean _pumpkin;
        public boolean _nutella;
        public int _itemindex;
        public double _totalwithouttax;
        public double _totalwithtax;
        public double _tax;
    }
    public Item[] order;
    private int _ordercount;
    public int _currentorder;
    private double _currenttotal;
    public double OrderTotal = 0;

    public happycup(int ordercount) {
        Simple_ice_cream s = new Simple_ice_cream();
        this._ordercount = ordercount;
        this._currentorder = 0;
        this.order = new Item[ordercount];
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        String z = s.cc();
        co.setText(z);
        this.lblTotal.setText(String.valueOf(ordercount));
        this.setTitle("Prepare order");
        this.setLocationRelativeTo(null);
        this.lblCurrent.setText(String.valueOf(this._currentorder + 1));
        if (_ordercount == 1) {
            btnNext.setVisible(false);
            btnBack.setVisible(false);
            btnFinish.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioVanilla = new javax.swing.JRadioButton();
        radiChocolate = new javax.swing.JRadioButton();
        radioStrawberry = new javax.swing.JRadioButton();
        radioToffe = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        txtSubTotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        buRest = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cNoTax = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        co = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        chAlmonds = new javax.swing.JCheckBox();
        chPeanut = new javax.swing.JCheckBox();
        chMint = new javax.swing.JCheckBox();
        chPeach = new javax.swing.JCheckBox();
        chLemon = new javax.swing.JCheckBox();
        chPumpkine = new javax.swing.JCheckBox();
        chNutella = new javax.swing.JCheckBox();

        jLabel7.setText("jLabel7");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/happycup/happycup400.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        radioVanilla.setBackground(new java.awt.Color(153, 153, 153));
        radioVanilla.setForeground(new java.awt.Color(255, 255, 255));
        radioVanilla.setText("CAPPUCCINO 8 S.R");
        radioVanilla.setActionCommand("8");
        radioVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVanillaActionPerformed(evt);
            }
        });

        radiChocolate.setBackground(new java.awt.Color(153, 153, 153));
        radiChocolate.setForeground(new java.awt.Color(255, 255, 255));
        radiChocolate.setText("LATTE 9 S.R");
        radiChocolate.setActionCommand("9");
        radiChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiChocolateActionPerformed(evt);
            }
        });

        radioStrawberry.setBackground(new java.awt.Color(153, 153, 153));
        radioStrawberry.setForeground(new java.awt.Color(255, 255, 255));
        radioStrawberry.setText("ESPRESSO 8 S.R");
        radioStrawberry.setActionCommand("8");
        radioStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStrawberryActionPerformed(evt);
            }
        });

        radioToffe.setBackground(new java.awt.Color(153, 153, 153));
        radioToffe.setForeground(new java.awt.Color(255, 255, 255));
        radioToffe.setText("COFE MOCHA 10 S.R");
        radioToffe.setActionCommand("10");
        radioToffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioToffeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioVanilla)
                    .addComponent(radioStrawberry)
                    .addComponent(radiChocolate)
                    .addComponent(radioToffe))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioVanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiChocolate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStrawberry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioToffe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.setForeground(new java.awt.Color(153, 153, 153));
        jPanel14.setAutoscrolls(true);

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        txtTax.setEditable(false);
        txtTax.setBackground(new java.awt.Color(255, 255, 255));
        txtTax.setForeground(new java.awt.Color(255, 0, 0));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("Item Total Without Tax");

        jLabel3.setText("Tax");

        jLabel4.setText("Item Total With Tax");

        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("S.R");

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        buRest.setText("Rest ");
        buRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buRestActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.setEnabled(false);
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setEnabled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelFocusLost(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buRest, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buRest)
                    .addComponent(btnFinish)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnCancel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cNoTax.setBackground(new java.awt.Color(153, 153, 153));
        cNoTax.setForeground(new java.awt.Color(255, 255, 51));
        cNoTax.setText("No TAX");
        cNoTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNoTaxActionPerformed(evt);
            }
        });

        jLabel14.setText("This Item");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cNoTax)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cNoTax))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Main");

        jLabel8.setText("Extra");

        co.setForeground(new java.awt.Color(255, 255, 255));
        co.setText("jLabel9");
        co.setToolTipText("");
        co.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        co.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Item");

        lblCurrent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCurrent.setForeground(new java.awt.Color(102, 102, 102));
        lblCurrent.setText("1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Of");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setText("5");

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        chAlmonds.setBackground(new java.awt.Color(153, 153, 153));
        chAlmonds.setForeground(new java.awt.Color(255, 255, 255));
        chAlmonds.setSelected(true);
        chAlmonds.setText("CUP CAKE 2 S.R");
        chAlmonds.setActionCommand("2");
        chAlmonds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPeanut.setBackground(new java.awt.Color(153, 153, 153));
        chPeanut.setForeground(new java.awt.Color(255, 255, 255));
        chPeanut.setText("DONUT 1.5 S.R");
        chPeanut.setActionCommand("1.5");
        chPeanut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chMint.setBackground(new java.awt.Color(153, 153, 153));
        chMint.setForeground(new java.awt.Color(255, 255, 255));
        chMint.setText("LOTUS 0.5 S.R");
        chMint.setActionCommand("0.5");
        chMint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPeach.setBackground(new java.awt.Color(153, 153, 153));
        chPeach.setForeground(new java.awt.Color(255, 255, 255));
        chPeach.setText("COOKIE 3 S.R");
        chPeach.setActionCommand("3");
        chPeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chLemon.setBackground(new java.awt.Color(153, 153, 153));
        chLemon.setForeground(new java.awt.Color(255, 255, 255));
        chLemon.setText("MAVEN 2 S.R");
        chLemon.setActionCommand("2");
        chLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPumpkine.setBackground(new java.awt.Color(153, 153, 153));
        chPumpkine.setForeground(new java.awt.Color(255, 255, 255));
        chPumpkine.setText("SOUFFLE 2.5 S.R");
        chPumpkine.setActionCommand("2.5");
        chPumpkine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chNutella.setBackground(new java.awt.Color(153, 153, 153));
        chNutella.setForeground(new java.awt.Color(255, 255, 255));
        chNutella.setText("BRAWNIE 4  S.R");
        chNutella.setActionCommand("4");
        chNutella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chAlmonds)
                    .addComponent(chPeanut)
                    .addComponent(chMint)
                    .addComponent(chPeach)
                    .addComponent(chLemon)
                    .addComponent(chPumpkine)
                    .addComponent(chNutella))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chAlmonds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPeanut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chMint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPeach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chLemon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPumpkine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chNutella)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(20, 20, 20)
                        .addComponent(lblTotal))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblCurrent)
                        .addComponent(jLabel12)
                        .addComponent(lblTotal)
                        .addComponent(jLabel8))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(co)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (this.isvalidInput()) {

            this.fillItem();

        } else {
            JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int i = 0; i < this._ordercount; i++) {
            this.OrderTotal += order[i]._totalwithtax;
        }

        MainScreen ms = new MainScreen(this._ordercount, this.OrderTotal, this);
        this.setVisible(false);
        ms.setVisible(true);
    }//GEN-LAST:event_btnFinishActionPerformed
    private void resetForm() {
        txtSubTotal.setText("");
        txtTax.setText("");
        txtTotal.setText("");
        cNoTax.setSelected(false);
        chAlmonds.setSelected(false);
        chPeanut.setSelected(false);
        chMint.setSelected(false);
        chPeach.setSelected(false);
        chLemon.setSelected(false);
        chPumpkine.setSelected(false);
        chNutella.setSelected(false);
        radioVanilla.setSelected(false);
        radiChocolate.setSelected(false);
        radioStrawberry.setSelected(false);
        radioToffe.setSelected(false);
    }
    private void buRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buRestActionPerformed
        this.resetForm();

    }//GEN-LAST:event_buRestActionPerformed

    private boolean isvalidInput() {
        return (radiChocolate.isSelected() || radioStrawberry.isSelected() || radioToffe.isSelected() || radioVanilla.isSelected());
    }

    private void fillItem() {
        double TAXRATE = .06;
        this.order[this._currentorder] = new Item();
        if (this.radiChocolate.isSelected()) {
            this.order[this._currentorder]._type = "Chocolate";
        } else if (this.radioStrawberry.isSelected()) {
            this.order[this._currentorder]._type = "Straberry";
        } else if (this.radioVanilla.isSelected()) {
            this.order[this._currentorder]._type = "Vanilla";
        } else if (this.radioToffe.isSelected()) {
            this.order[this._currentorder]._type = "Toffe";
        }
        this.order[this._currentorder]._almonds = chAlmonds.isSelected();
        this.order[this._currentorder]._lemon = chLemon.isSelected();
        this.order[this._currentorder]._mint = chMint.isSelected();
        this.order[this._currentorder]._nutella = chNutella.isSelected();
        this.order[this._currentorder]._peach = chPeach.isSelected();
        this.order[this._currentorder]._peanut = chPeanut.isSelected();
        this.order[this._currentorder]._pumpkin = chPumpkine.isSelected();
        if (this.cNoTax.isSelected()) {
            this.order[this._currentorder]._tax = 0;
            this.order[this._currentorder]._totalwithouttax = this._currenttotal;
            this.order[this._currentorder]._totalwithtax = this._currenttotal;
        } else {
            this.order[this._currentorder]._tax = this._currenttotal * TAXRATE;
            this.order[this._currentorder]._totalwithouttax = this._currenttotal;
            this.order[this._currentorder]._totalwithtax = this._currenttotal + (this._currenttotal * TAXRATE);
        }

    }

    private void fillForm() {
        if (this.order[this._currentorder] != null) {
            if (this.order[this._currentorder]._type == "Chocolate") {
                this.radiChocolate.setSelected(true);
            } else if (this.order[this._currentorder]._type == "Straberry") {
                this.radioStrawberry.setSelected(true);
            } else if (this.order[this._currentorder]._type == "Vanilla") {
                this.radioVanilla.setSelected(true);
            } else if (this.order[this._currentorder]._type == "Toffe") {
                this.radioToffe.setSelected(true);
            }
            chAlmonds.setSelected(this.order[this._currentorder]._almonds);
            chLemon.setSelected(this.order[this._currentorder]._lemon);
            chMint.setSelected(this.order[this._currentorder]._mint);
            chNutella.setSelected(this.order[this._currentorder]._nutella);
            chPeach.setSelected(this.order[this._currentorder]._peach);
            chPeanut.setSelected(this.order[this._currentorder]._peanut);
            chPumpkine.setSelected(this.order[this._currentorder]._pumpkin);

            if (this.order[this._currentorder]._tax > 0) {
                this.cNoTax.setSelected(true);
                txtSubTotal.setText(String.valueOf(this.order[this._currentorder]._totalwithouttax));
                txtTax.setText(String.valueOf(this.order[this._currentorder]._tax));
                txtTotal.setText(String.valueOf(this.order[this._currentorder]._totalwithtax));

            } else {
                this.cNoTax.setSelected(false);
                txtSubTotal.setText(String.valueOf(this.order[this._currentorder]._totalwithouttax));
                txtTax.setText(String.valueOf(this.order[this._currentorder]._tax));
                txtTotal.setText(String.valueOf(this.order[this._currentorder]._totalwithtax));
            }
        }
        this.lblCurrent.setText(String.valueOf(this._currentorder + 1));
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (this._currentorder + 2 == this._ordercount) {
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(true);
                this.btnNext.setEnabled(false);
                btnBack.setEnabled(true);

                this.fillItem();
                this.resetForm();

                this._currentorder++;
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {

            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);

                this.fillItem();
                this.resetForm();
                this._currentorder++;
                if (this._currentorder == 0) {
                    btnBack.setEnabled(false);
                } else {
                    btnBack.setEnabled(true);
                }
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }


    }//GEN-LAST:event_btnNextActionPerformed
    private void recalculate() {
        double total;
        double subtotal = 0;
        double TAXRATE = .06;
        double tax;

        if (cNoTax.isSelected()) {
            TAXRATE = 0;
        }
        if (radioVanilla.isSelected()) {
            subtotal = subtotal + 8;
        } else if (radiChocolate.isSelected()) {
            subtotal = subtotal + 9;
        } else if (radioStrawberry.isSelected()) {
            subtotal = subtotal + 8;
        } else if (radioToffe.isSelected()) {
            subtotal = subtotal + 10;
        }

        if (chAlmonds.isSelected()) {
            subtotal = subtotal + 2;
        }
        if (chPeanut.isSelected()) {
            subtotal = subtotal + 1.5;
        }
        if (chMint.isSelected()) {
            subtotal = subtotal + 0.5;
        }
        if (chPeach.isSelected()) {
            subtotal = subtotal + 3;
        }
        if (chLemon.isSelected()) {
            subtotal = subtotal + 2;
        }
        if (chPumpkine.isSelected()) {
            subtotal = subtotal + 2.5;
        }
        if (chNutella.isSelected()) {
            subtotal = subtotal + 4;
        }

        txtSubTotal.setText(Double.toString(subtotal));

        subtotal = Double.parseDouble(txtSubTotal.getText());
        this._currenttotal = subtotal;
        tax = (subtotal * TAXRATE);
        DecimalFormat df = new DecimalFormat("#.##");
        tax = Double.valueOf(df.format(tax));
        total = tax + subtotal;

        txtTax.setText(Double.toString(tax));
        txtTotal.setText(Double.toString(total));
    }
    private void radioToffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioToffeActionPerformed
        if (radioToffe.isSelected()) {
            radioVanilla.setSelected(false);
            radiChocolate.setSelected(false);
            radioStrawberry.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioToffeActionPerformed

    private void radioStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStrawberryActionPerformed
        if (radioStrawberry.isSelected()) {
            radioVanilla.setSelected(false);
            radiChocolate.setSelected(false);
            radioToffe.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioStrawberryActionPerformed

    private void radiChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiChocolateActionPerformed
        if (radiChocolate.isSelected()) {
            radioVanilla.setSelected(false);
            radioStrawberry.setSelected(false);
            radioToffe.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radiChocolateActionPerformed

    private void radioVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVanillaActionPerformed
        if (radioVanilla.isSelected()) {
            radiChocolate.setSelected(false);
            radioStrawberry.setSelected(false);
            radioToffe.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioVanillaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (this._currentorder - 1 == 0) {
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);
                this.btnNext.setEnabled(true);
                btnBack.setEnabled(false);

                this.fillItem();
                this.resetForm();
                this._currentorder--;
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {
            if (this._currentorder == 0) {
                return;
            }
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);
                btnBack.setEnabled(true);
                this.fillItem();
                this.resetForm();
                this._currentorder--;
                this.fillForm();

            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void chAlmondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAlmondsActionPerformed
        // TODO add your handling code here:
        recalculate();
    }//GEN-LAST:event_chAlmondsActionPerformed

    private void cNoTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNoTaxActionPerformed
        // TODO add your handling code here:
        recalculate();
    }//GEN-LAST:event_cNoTaxActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         MainScreen ms = new MainScreen();
         ms.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton buRest;
    private javax.swing.JCheckBox cNoTax;
    private javax.swing.JCheckBox chAlmonds;
    private javax.swing.JCheckBox chLemon;
    private javax.swing.JCheckBox chMint;
    private javax.swing.JCheckBox chNutella;
    private javax.swing.JCheckBox chPeach;
    private javax.swing.JCheckBox chPeanut;
    private javax.swing.JCheckBox chPumpkine;
    private javax.swing.JLabel co;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton radiChocolate;
    private javax.swing.JRadioButton radioStrawberry;
    private javax.swing.JRadioButton radioToffe;
    private javax.swing.JRadioButton radioVanilla;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
